version: '3.4'
services:
  build-env:
    ports:
      - "5000:5000"
      - "9005:9005"
    image: flow-example-project/flow-example-project:latest
    volumes:
      - "./:/var/build"
    command: "bash -c 'sleep infinity'"
